import { ukSources } from "./articles/uk";
import { ukSourcesMap } from "./articles/uk/sources";
import {
	floridaSources,
	floridaSourcesMap,
} from "./articles/united-states/florida";
import {
	ny_sources,
	ny_sourcesMap,
} from "./articles/united-states/newyork-sources";

import {
	abc,
	abcAustralia,
	afp,
	aljazeera,
	arabNews,
	bbcNews,
	bloomberg,
	bostonHerald,
	breitbart,
	buzzfeed,
	bylineTimes,
	cbc,
	cbs,
	channel4,
	channel5,
	channelNewsAsia,
	cnbc,
	cnn,
	councilEstateMedia,
	dailyMail,
	dailyWire,
	declassiied,
	democracyNow,
	denverPost,
	doubleDownNews,
	dropSiteNews,
	dw,
	eInternationalRelations,
	electronicIntifada,
	euronews,
	eveningStandard,
	express,
	firstPost,
	fox,
	france24,
	ft,
	gbNews,
	globalIssues,
	globalNews,
	globeAndMail,
	guardian,
	haaretz,
	huffpost,
	ifpNews,
	independent,
	itv,
	japanTimes,
	kyivIndependent,
	laTimes,
	mercuryNews,
	metro,
	middleEastEye,
	mintPressNews,
	mirror,
	nbc,
	ndtv,
	news24,
	newYorkPost,
	newYorkTimes,
	northernIrelandWorld,
	novara,
	npr,
	owenJones,
	palestineChronicle,
	palestineNewsNetwork,
	pbs,
	politico,
	politicsCoUk,
	proPublica,
	qudsNews,
	rawStory,
	reuters,
	revealNews,
	rollingStone,
	royaNews,
	rt,
	sabc,
	seatleTimes,
	sheffieldTribune,
	skyNews,
	slate,
	southChinaMorningPost,
	sputnik,
	straitsTimes,
	sydneyMorningHerald,
	telegraph,
	tennesseeHoller,
	theAmericanConservative,
	theAtlantic,
	theBulwark,
	theCipherBrief,
	theConversation,
	theCradle,
	theDailyBeast,
	theDailyCaller,
	theDiplomat,
	theEconomist,
	theFederalist,
	theGrayZone,
	theHill,
	theIntellectualist,
	theIntercept,
	theMoscowTimes,
	theNewHumanitarian,
	theNewYorker,
	theOnion,
	thePinkNews,
	theStar,
	theSun,
	theTimes,
	theWorld,
	time,
	timesofindia,
	timesOfIsrael,
	tldr,
	torontoStar,
	trt,
	truthOut,
	un,
	usatoday,
	usNews,
	verge,
	vox,
	walesOnline,
	wallStreetJournal,
	washingtonPost,
	washingtonTimes,
	yahoo,
	zeteo,
} from "./providers/providers";
export const NewsSources = {
	ARAB_NEWS: "Arab News",
	BBC: "BBC",
	GUARDIAN: "The Guardian",
	TELEGRAPH: "The Telegraph",
	MIRROR: "The Mirror",
	DAILY_MAIL: "The Daily Mail",
	METRO: "Metro",
	EVENING_STANDARD: "The Evening Standard",
	SUN: "The Sun",
	SKY: "Sky News",
	TIMES: "Times",
	INDEPENDENT: "The Independent",
	HUFFPOST: "The Huffington Post",
	POLITICS_CO_UK: "politics.co.uk",
	THE_CONVERSATION: "The Conversation",
	THE_PINK_NEWS: "The Pink News",
	NORTHERN_IRELAND_WORLD: "Northern Ireland World",
	WALES_ONLINE: "Wales Online",
	GB_NEWS: "GB News",
	FT: "FT",

	CNN: "CNN",
	FOX: "Fox News",
	WALL_STREET_JOURNAL: "The Wall Street Journal",
	YAHOO: "Yahoo News",
	NPR: "NPR",
	WASHINGTON_TIMES: "Washington Times",
	LA_TIMES: "LA Times",
	MERCURY_NEWS: "Mercury News",
	CBS: "CBS",
	ABC: "ABC",
	BREITBART: "Breitbart",
	BOSTON_HEARLD: "Boston Herald",
	DENVER_POST: "Denver Post",
	NEW_YORK_POST: "New York Post",
	THE_HILL: "The Hill",
	POLITICO: "Politico",
	VOX: "Vox",
	BUZZFEED: "Buzzfeed",
	THE_ATLANTIC: "The Atlantic",
	SEATTLE_TIMES: "Seattle Times",
	INTERCEPT: "The Intercept",
	VERGE: "The Verge",
	THE_DAILY_BEAST: "The Daily Beast",
	THE_NEW_YORKER: "The New Yorker",
	THE_ONION: "The Onion",
	THE_DAILY_CALLER: "The Daily Caller",
	THE_FEDERALIST: "The Federalist",
	THE_AMERICAN_CONSERVATIVE: "The American Conservative",
	THE_BULWARK: "The Bulwark",
	NEW_YORK_TIMES: "New York Times",

	AL_JAZEERA: "Al Jazeera",
	WASHINGTON_POST: "The Washington Post",
	CNBC: "CNBC",
	CBC: "CBC",
	DEUTSCHE_WELLE: "Deutsche Welle",
	FRANCE_24: "France 24",
	US_NEWS: "US News",
	GLOBAL_NEWS: "Global News",
	TIME: "Time",
	USA_TODAY: "USA Today",
	SYDNEY_MORNING_HERALD: "Sydney Morning Herald",
	GLOBE_AND_MAIL: "Globe and Mail",
	TORONTO_STAR: "Toronto Star",
	JAPAN_TIMES: "Japan Times",
	SOUTH_CHINA_MORNING_POST: "South China Morning Post",
	STRAITS_TIMES: "Straits Times",
	TIMES_OF_INDIA: "Times of India",
	RT: "RT",
	NDTV: "NDTV",
	E_INTERNATIONAL_RELATIONS: "E-International Relations",
	CIPHER_BRIEF: "The Cipher Brief",
	EXPRESS: "Daily Express",
	EURONEWS: "Euronews",
	CHANNEL_NEWS_ASIA: "Channel News Asia",
	NEWS_24: "News24",
	THE_DIPLOMAT: "The Diplomat",
	MOSCOW_TIMES: "The Moscow Times",
	THE_NEW_HUMANITARIAN: "The New Humanitarian",
	RAW_STORY: "Raw Story",
	IFP_NEWS: "IFP News",
	SCMP: "South China Morning Post",
	THE_WORLD: "The World",
	SPUTNIK: "Sputnik",
	AP: "Associated Press",
	GLOBAL_ISSUES: "Global Issues",
	UN: "United Nations",

	ITV: "ITV",
	CHANNEL_4: "Channel 4",
	CHANNEL_5: "Channel 5",

	NBC: "NBC",
	PBS: "PBS",
	REUTERS: "Reuters",
	PRO_PUBLICA: "ProPublica",
	DEMOCRACY_NOW: "Democracy Now",
	BLOOMBERG: "Bloomberg",
	NINE_NEWS: "9News",
	ABC_AUSTRALIA: "ABC AUS",
	FIRST_POST: "First Post",
	AFP: "AFP",
	TRT: "TRT",
	SABC: "SABC",

	TLDR: "TLDR News",

	//
	THE_STAR: "The Star",
	SHEFFIELD_TRIBUNE: "The Sheffield Tribune",

	// Audio
	THE_ECONOMIST: "The Economist",

	NOVARA: "Novara Media",
	KYIV_INDEPENDENT: "Kyiv Independent",

	DECLASSIFIED: "Declassified UK",
	TENNESSEE_HOLLER: "Tennessee Holler",

	THE_INTELLECTUALIST: "The Intellectualist",
	DROP_SITE_NEWS: "Drop Site News",
	GRAY_ZONE: "The Gray Zone",
	ELECTRONIC_INTIFADA: "Electronic Intifada",
	QUDS_NEWS: "Quds News",
	TIMES_OF_ISRAEL: "The Times Of Israel",
	HAARETZ: "Haaretz",
	MIDDLE_EAST_EYE: "Middle East Eye",
	ROLLING_STONE: "Rolling Stone",
	MINT_PRESS_NEWS: "Mint Press News",
	TRUTHOUT: "Truthout",
	REVEAL_NEWS: "Reveal News",
	BYLINE_TIMES: "Byline Times",
	COUNCIL_ESTATE_MEDIA: "Council Estate Media",
	DAILY_WIRE: "Daily Wire",
	SLATE: "Slate",
	OWEN_JONES: "Owen Jones",
	DOUBLE_DOWN_NEWS: "Double Down News",
	THE_CRADLE: "The Cradle",
	ROYA_NEWS: "Roya News",
	ZETEO: "Zeteo",
	PALESTINE_CHRONICLE: "Palestine Chronicle",
	PALESTINE_NEWS_NETWORK: "Palestine News Network",

	...ukSources,

	...ny_sources,
	...floridaSources,
} as const;

// Split these up and spread in the map as this is a bit of a mess
// We can type better
export const newsSourcesMap = new Map<string, any>([
	[NewsSources.ARAB_NEWS, arabNews],
	[NewsSources.BBC, bbcNews],
	[NewsSources.GUARDIAN, guardian],
	[NewsSources.TELEGRAPH, telegraph],
	[NewsSources.MIRROR, mirror],
	[NewsSources.DAILY_MAIL, dailyMail],
	[NewsSources.METRO, metro],
	[NewsSources.EVENING_STANDARD, eveningStandard],
	[NewsSources.SUN, theSun],
	[NewsSources.SKY, skyNews],
	[NewsSources.INDEPENDENT, independent],
	[NewsSources.HUFFPOST, huffpost],
	[NewsSources.POLITICS_CO_UK, politicsCoUk],
	[NewsSources.THE_CONVERSATION, theConversation],
	[NewsSources.THE_PINK_NEWS, thePinkNews],
	[NewsSources.NORTHERN_IRELAND_WORLD, northernIrelandWorld],
	[NewsSources.WALES_ONLINE, walesOnline],
	[NewsSources.GB_NEWS, gbNews],
	[NewsSources.CNN, cnn],
	[NewsSources.FOX, fox],
	[NewsSources.WALL_STREET_JOURNAL, wallStreetJournal],
	[NewsSources.YAHOO, yahoo],
	[NewsSources.NPR, npr],
	[NewsSources.WASHINGTON_TIMES, washingtonTimes],
	[NewsSources.LA_TIMES, laTimes],
	[NewsSources.MERCURY_NEWS, mercuryNews],
	[NewsSources.CBS, cbs],
	[NewsSources.ABC, abc],
	[NewsSources.BREITBART, breitbart],
	[NewsSources.BOSTON_HEARLD, bostonHerald],
	[NewsSources.DENVER_POST, denverPost],
	[NewsSources.NEW_YORK_POST, newYorkPost],
	[NewsSources.THE_HILL, theHill],
	[NewsSources.POLITICO, politico],
	[NewsSources.VOX, vox],
	[NewsSources.BUZZFEED, buzzfeed],
	[NewsSources.THE_ATLANTIC, theAtlantic],
	[NewsSources.SEATTLE_TIMES, seatleTimes],
	[NewsSources.INTERCEPT, theIntercept],
	[NewsSources.VERGE, verge],
	[NewsSources.THE_DAILY_BEAST, theDailyBeast],
	[NewsSources.THE_NEW_YORKER, theNewYorker],
	[NewsSources.THE_ONION, theOnion],
	[NewsSources.THE_DAILY_CALLER, theDailyCaller],
	[NewsSources.THE_FEDERALIST, theFederalist],
	[NewsSources.THE_AMERICAN_CONSERVATIVE, theAmericanConservative],
	[NewsSources.THE_BULWARK, theBulwark],
	[NewsSources.NEW_YORK_TIMES, newYorkTimes],
	[NewsSources.AL_JAZEERA, aljazeera],
	[NewsSources.WASHINGTON_POST, washingtonPost],
	[NewsSources.CNBC, cnbc],
	[NewsSources.CBC, cbc],
	[NewsSources.DEUTSCHE_WELLE, dw],
	[NewsSources.FRANCE_24, france24],
	[NewsSources.US_NEWS, usNews],
	[NewsSources.GLOBAL_NEWS, globalNews],
	[NewsSources.TIME, time],
	[NewsSources.USA_TODAY, usatoday],
	[NewsSources.SYDNEY_MORNING_HERALD, sydneyMorningHerald],
	[NewsSources.GLOBE_AND_MAIL, globeAndMail],
	[NewsSources.TORONTO_STAR, torontoStar],
	[NewsSources.JAPAN_TIMES, japanTimes],
	[NewsSources.SOUTH_CHINA_MORNING_POST, southChinaMorningPost],
	[NewsSources.STRAITS_TIMES, straitsTimes],
	[NewsSources.TIMES_OF_INDIA, timesofindia],
	[NewsSources.RT, rt],
	[NewsSources.NDTV, ndtv],
	[NewsSources.E_INTERNATIONAL_RELATIONS, eInternationalRelations],
	[NewsSources.CIPHER_BRIEF, theCipherBrief],
	[NewsSources.EXPRESS, express],
	[NewsSources.EURONEWS, euronews],
	[NewsSources.CHANNEL_NEWS_ASIA, channelNewsAsia],
	[NewsSources.NEWS_24, news24],
	[NewsSources.THE_DIPLOMAT, theDiplomat],
	[NewsSources.MOSCOW_TIMES, theMoscowTimes],
	[NewsSources.THE_NEW_HUMANITARIAN, theNewHumanitarian],
	[NewsSources.RAW_STORY, rawStory],
	[NewsSources.IFP_NEWS, ifpNews],
	[NewsSources.SCMP, southChinaMorningPost],
	[NewsSources.THE_WORLD, theWorld],
	[NewsSources.SPUTNIK, sputnik],
	[NewsSources.GLOBAL_ISSUES, globalIssues],
	[NewsSources.UN, un],
	[NewsSources.ITV, itv],
	[NewsSources.CHANNEL_4, channel4],
	[NewsSources.CHANNEL_5, channel5],
	[NewsSources.NBC, nbc],
	[NewsSources.PBS, pbs],
	[NewsSources.REUTERS, reuters],
	[NewsSources.PRO_PUBLICA, proPublica],
	[NewsSources.DEMOCRACY_NOW, democracyNow],
	[NewsSources.BLOOMBERG, bloomberg],
	[NewsSources.NINE_NEWS, nbc],

	[NewsSources.ABC_AUSTRALIA, abcAustralia],
	[NewsSources.FIRST_POST, firstPost],
	[NewsSources.AFP, afp],
	[NewsSources.TRT, trt],
	[NewsSources.SABC, sabc],

	[NewsSources.THE_STAR, theStar],
	[NewsSources.SHEFFIELD_TRIBUNE, sheffieldTribune],

	[NewsSources.TIMES, theTimes],
	[NewsSources.TLDR, tldr],

	[NewsSources.THE_ECONOMIST, theEconomist],
	[NewsSources.FT, ft],

	[NewsSources.NOVARA, novara],
	[NewsSources.KYIV_INDEPENDENT, kyivIndependent],
	[NewsSources.DECLASSIFIED, declassiied],
	[NewsSources.TENNESSEE_HOLLER, tennesseeHoller],
	[NewsSources.THE_INTELLECTUALIST, theIntellectualist],
	[NewsSources.DROP_SITE_NEWS, dropSiteNews],
	[NewsSources.GRAY_ZONE, theGrayZone],
	[NewsSources.ELECTRONIC_INTIFADA, electronicIntifada],
	[NewsSources.QUDS_NEWS, qudsNews],
	[NewsSources.TIMES_OF_ISRAEL, timesOfIsrael],
	[NewsSources.HAARETZ, haaretz],
	[NewsSources.MIDDLE_EAST_EYE, middleEastEye],
	[NewsSources.ROLLING_STONE, rollingStone],
	[NewsSources.MINT_PRESS_NEWS, mintPressNews],
	[NewsSources.TRUTHOUT, truthOut],
	[NewsSources.REVEAL_NEWS, revealNews],
	[NewsSources.BYLINE_TIMES, bylineTimes],
	[NewsSources.COUNCIL_ESTATE_MEDIA, councilEstateMedia],
	[NewsSources.DAILY_WIRE, dailyWire],
	[NewsSources.SLATE, slate],
	[NewsSources.OWEN_JONES, owenJones],
	[NewsSources.DOUBLE_DOWN_NEWS, doubleDownNews],
	[NewsSources.THE_CRADLE, theCradle],
	[NewsSources.ROYA_NEWS, royaNews],
	[NewsSources.ZETEO, zeteo],
	[NewsSources.PALESTINE_CHRONICLE, palestineChronicle],
	[NewsSources.PALESTINE_NEWS_NETWORK, palestineNewsNetwork],

	...ukSourcesMap,
	...ny_sourcesMap,
	...floridaSourcesMap,
]);
