import { SourceVariant, TimeFunction, FetchFunction, CronType } from "../types";

export const podcastRSSCronQueriesConfig = {
	id: "Podcast RSS Cron Queries",
	type: CronType.RSS,
	cron: [
		{
			titles: ["UK News Bites"],
			variant: SourceVariant.AUDIO,
			timeFunction: TimeFunction.StaggerMinutes,
			timeParams: [15, 8, 0],
			fetchFunction: FetchFunction.Podcasts,
			onComplete: () => {},
		},
		{
			titles: ["US News Bites"],
			variant: SourceVariant.AUDIO,
			timeFunction: TimeFunction.StaggerMinutes,
			timeParams: [15, 8, 30],
			fetchFunction: FetchFunction.Podcasts,
			onComplete: () => {},
		},
		{
			titles: ["World News Bites"],
			variant: SourceVariant.AUDIO,
			timeFunction: TimeFunction.StaggerMinutes,
			timeParams: [15, 9, 0],
			fetchFunction: FetchFunction.Podcasts,
			onComplete: () => {},
		},
		{
			titles: ["UK News Audio 1"],
			variant: SourceVariant.AUDIO,
			timeFunction: TimeFunction.EveryNthHour,
			timeParams: [6, 9, 30],
			fetchFunction: FetchFunction.Podcasts,
			onComplete: () => {},
		},
		{
			titles: ["UK News Audio 2"],
			variant: SourceVariant.AUDIO,
			timeFunction: TimeFunction.EveryNthHour,
			timeParams: [6, 10, 0],
			fetchFunction: FetchFunction.Podcasts,
			onComplete: () => {},
		},
		{
			titles: ["US News Audio 1"],
			variant: SourceVariant.AUDIO,
			timeFunction: TimeFunction.EveryNthHour,
			timeParams: [6, 10, 30],
			fetchFunction: FetchFunction.Podcasts,
			onComplete: () => {},
		},
		{
			titles: ["US News Audio 2"],
			variant: SourceVariant.AUDIO,
			timeFunction: TimeFunction.EveryNthHour,
			timeParams: [6, 11, 0],
			fetchFunction: FetchFunction.Podcasts,
			onComplete: () => {},
		},
		{
			titles: ["US News Audio 3"],
			variant: SourceVariant.AUDIO,
			timeFunction: TimeFunction.EveryNthHour,
			timeParams: [6, 11, 30],
			fetchFunction: FetchFunction.Podcasts,
			onComplete: () => {},
		},
		{
			titles: ["US News Audio 4"],
			variant: SourceVariant.AUDIO,
			timeFunction: TimeFunction.EveryNthHour,
			timeParams: [6, 12, 0],
			fetchFunction: FetchFunction.Podcasts,
			onComplete: () => {},
		},
		{
			titles: ["World News Audio 1"],
			variant: SourceVariant.AUDIO,
			timeFunction: TimeFunction.EveryNthHour,
			timeParams: [6, 12, 30],
			fetchFunction: FetchFunction.Podcasts,
			onComplete: () => {},
		},
		{
			titles: ["World News Audio 2"],
			variant: SourceVariant.AUDIO,
			timeFunction: TimeFunction.EveryNthHour,
			timeParams: [6, 13, 0],
			fetchFunction: FetchFunction.Podcasts,
			onComplete: () => {},
		},
	],
};
