import { SourceVariant, TimeFunction, FetchFunction, CronType } from "../types";

export const RSSCronQueriesConfig = {
	id: "RSS Cron Queries",
	type: CronType.RSS,
	cron: [
		{
			titles: ["US National Articles 1", "US National Articles 2"],
			variant: SourceVariant.ARTICLE,
			timeFunction: TimeFunction.StaggerMinutes,
			timeParams: [15, 3, 0],
			fetchFunction: FetchFunction.RSS,
			onComplete: () => {},
		},
		{
			titles: [
				"US National Articles 3",
				"US National Articles 4",
				"US National Articles 5",
			],
			variant: SourceVariant.ARTICLE,
			timeFunction: TimeFunction.StaggerMinutes,
			timeParams: [15, 3, 30],
			fetchFunction: FetchFunction.RSS,
			onComplete: () => {},
		},
		{
			titles: ["World Articles 1", "World Articles 2"],
			variant: SourceVariant.ARTICLE,
			timeFunction: TimeFunction.StaggerMinutes,
			timeParams: [15, 4, 0],
			fetchFunction: FetchFunction.RSS,
			onComplete: () => {},
		},
		{
			titles: ["World Articles 3", "World Articles 4", "World Articles 5"],
			variant: SourceVariant.ARTICLE,
			timeFunction: TimeFunction.StaggerMinutes,
			timeParams: [15, 4, 30],
			fetchFunction: FetchFunction.RSS,
			onComplete: () => {},
		},
		{
			titles: ["World Articles 5", "World Articles 6", "World Articles 7"],
			variant: SourceVariant.ARTICLE,
			timeFunction: TimeFunction.StaggerMinutes,
			timeParams: [15, 5],
			fetchFunction: FetchFunction.RSS,
			onComplete: () => {},
		},
		{
			titles: ["New York Articles"],
			variant: SourceVariant.ARTICLE,
			timeFunction: TimeFunction.StaggerMinutes,
			timeParams: [30, 5, 30],
			fetchFunction: FetchFunction.RSS,
			onComplete: () => {},
		},
		{
			titles: ["New York Video News"],
			variant: SourceVariant.VIDEO,
			timeFunction: TimeFunction.StaggerMinutes,
			timeParams: [30, 6, 0],
			fetchFunction: FetchFunction.YoutubeRSS,
			onComplete: () => {},
		},
		{
			titles: ["Florida Articles"],
			variant: SourceVariant.ARTICLE,
			timeFunction: TimeFunction.StaggerMinutes,
			timeParams: [30, 6, 30],
			fetchFunction: FetchFunction.RSS,
			onComplete: () => {},
		},
		{
			titles: ["Florida Video News"],
			variant: SourceVariant.VIDEO,
			timeFunction: TimeFunction.StaggerMinutes,
			timeParams: [30, 6, 0],
			fetchFunction: FetchFunction.YoutubeRSS,
			onComplete: () => {},
		},
		{
			titles: [
				"US Video News",
				"US Video News 2",
				"US Live Video",
				"World Video News",
				"World Video News 2",
				"World Live Video",
			],
			variant: SourceVariant.VIDEO,
			timeFunction: TimeFunction.StaggerMinutes,
			timeParams: [15, 7, 0],
			fetchFunction: FetchFunction.YoutubeRSS,
			onComplete: () => {},
		},
	],
};
